# Generated by Django 4.2.3 on 2023-09-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='Date_Acquisition',
            field=models.DateField(),
        ),
    ]
