# Generated by Django 4.2.3 on 2023-09-01 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Equipement', '0002_alter_equipement_date_acquisition'),
        ('Visiteur', '0002_messagereservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereservation',
            name='equipement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Equipement.equipement'),
            preserve_default=False,
        ),
    ]
