# Generated by Django 4.2.3 on 2023-09-05 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_superuser',
        ),
    ]
