# Generated by Django 4.2.3 on 2023-09-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0007_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('gestionnaire', 'Gestionnaire'), ('administrateur', 'Administrateur'), ('visiteur', 'Visiteur')], default='visiteur', max_length=20),
        ),
    ]
